/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PreviewGrowthRouteImport } from './routes/preview-growth'
import { Route as StoryRouteImport } from './routes/story'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as EmployerCandidateIdRouteImport } from './routes/employer.$candidateId'
import { Route as MissionSkillIdRouteImport } from './routes/mission.$skillId'
import { Route as SkillsSkillIdRouteImport } from './routes/skills.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewGrowthRoute = PreviewGrowthRouteImport.update({
  id: '/preview-growth',
  path: '/preview-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCandidateIdRoute = EmployerCandidateIdRouteImport.update({
  id: '/$candidateId',
  path: '/$candidateId',
  getParentRoute: () => EmployerRoute,
} as any)
const MissionSkillIdRoute = MissionSkillIdRouteImport.update({
  id: '/mission/$skillId',
  path: '/mission/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/employer': typeof EmployerRouteWithChildren
  '/opportunities': typeof OpportunitiesRoute
  '/preview-growth': typeof PreviewGrowthRoute
  '/story': typeof StoryRoute
  '/employer/$candidateId': typeof EmployerCandidateIdRoute
  '/mission/$skillId': typeof MissionSkillIdRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/employer/': typeof EmployerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/opportunities': typeof OpportunitiesRoute
  '/preview-growth': typeof PreviewGrowthRoute
  '/story': typeof StoryRoute
  '/employer/$candidateId': typeof EmployerCandidateIdRoute
  '/mission/$skillId': typeof MissionSkillIdRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/employer': typeof EmployerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/employer': typeof EmployerRouteWithChildren
  '/opportunities': typeof OpportunitiesRoute
  '/preview-growth': typeof PreviewGrowthRoute
  '/story': typeof StoryRoute
  '/employer/$candidateId': typeof EmployerCandidateIdRoute
  '/mission/$skillId': typeof MissionSkillIdRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/employer/': typeof EmployerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/employer'
    | '/opportunities'
    | '/preview-growth'
    | '/story'
    | '/employer/$candidateId'
    | '/mission/$skillId'
    | '/skills/$skillId'
    | '/employer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/discover'
    | '/opportunities'
    | '/preview-growth'
    | '/story'
    | '/employer/$candidateId'
    | '/mission/$skillId'
    | '/skills/$skillId'
    | '/employer'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/discover'
    | '/employer'
    | '/opportunities'
    | '/preview-growth'
    | '/story'
    | '/employer/$candidateId'
    | '/mission/$skillId'
    | '/skills/$skillId'
    | '/employer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  EmployerRoute: typeof EmployerRouteWithChildren
  OpportunitiesRoute: typeof OpportunitiesRoute
  PreviewGrowthRoute: typeof PreviewGrowthRoute
  StoryRoute: typeof StoryRoute
  MissionSkillIdRoute: typeof MissionSkillIdRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-growth': {
      id: '/preview-growth'
      path: '/preview-growth'
      fullPath: '/preview-growth'
      preLoaderRoute: typeof PreviewGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/$candidateId': {
      id: '/employer/$candidateId'
      path: '/$candidateId'
      fullPath: '/employer/$candidateId'
      preLoaderRoute: typeof EmployerCandidateIdRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/mission/$skillId': {
      id: '/mission/$skillId'
      path: '/mission/$skillId'
      fullPath: '/mission/$skillId'
      preLoaderRoute: typeof MissionSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmployerRouteChildren {
  EmployerCandidateIdRoute: typeof EmployerCandidateIdRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerCandidateIdRoute: EmployerCandidateIdRoute,
  EmployerIndexRoute: EmployerIndexRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  EmployerRoute: EmployerRouteWithChildren,
  OpportunitiesRoute: OpportunitiesRoute,
  PreviewGrowthRoute: PreviewGrowthRoute,
  StoryRoute: StoryRoute,
  MissionSkillIdRoute: MissionSkillIdRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
